### ISSUE TITLE
SDK is not supported by the compiler 

### ISSUE THREAD

**Issue by luisrodrigo** [innovatrics/dot-ios-sdk-samples#1]
Minimal requirements indicate Xcode 11+ but when I try compile with Xcode 13.2 appear a error message like: "Failed to build module 'DotFaceCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK. "

Which indicate compilation with Xcode 14+ ( Apple swift version 5.7) . How I can fix it?

**Comment by jakub-vallo** [comment]
Hi,
thanks for reporting the issue, we are aware of this. There is wrong Xcode version in the minimal requirements of the latest release of DOT Face 4.11.0. The correct minimal version is Xcode 14+. There are two possible workarounds: 1. use previous version of DOT Face; 2. update to Xcode 14+.
