### ISSUE TITLE
FaceAutoCapture crash 

### ISSUE THREAD

**Issue by amalive** [innovatrics/dot-ios-sdk-samples#2]
Recently I got this error when capturing face: 
DotFaceCore/FaceAutoCaptureViewController.swift:131: Fatal error: 'try!' expression unexpectedly raised an error: DotFaceCore.DotFaceModuleLoader.Error.moduleNotAvailable

xcode: 14.3

**Comment by jakub-vallo** [comment]
It means one of the reqiured modules is missing, please see https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-ios-face/latest/documentation/ for more details.
